config/routes.rb
Myforum::Application.routes.draw do

  resources :forums, :has_many => :topics
resources :topics, :has_many => :replies
resources :replies

resources  :forums do
    resources :topics
end

resources  :topics do
    resources :replies
end

root :controller => 'forums', :action => 'index'

end

app/models/forum.rb
class Forum < ActiveRecord::Base  
has_many :topics  
has_many :replies, :through => :topics
end

app/models/reply.rb
class Reply < ActiveRecord::Base 
 belongs_to :topic  
belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base  
belongs_to :forum  
belongs_to :user  
has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  # GET /forums
  # GET /forums.xml
  def index
    @forums = Forum.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @forums }
    end
  end

  # GET /forums/1
  # GET /forums/1.xml
  def show
    @forum = Forum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @forum }
    end
  end

  # GET /forums/new
  # GET /forums/new.xml
  def new
    @forum = Forum.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @forum }
    end
  end

  # GET /forums/1/edit
  def edit
    @forum = Forum.find(params[:id])
  end

  # POST /forums
  # POST /forums.xml
  def create
    @forum = Forum.new(params[:forum])

    respond_to do |format|
      if @forum.save
        format.html { redirect_to(@forum, :notice => 'Forum was successfully created.') }
        format.xml  { render :xml => @forum, :status => :created, :location => @forum }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @forum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /forums/1
  # PUT /forums/1.xml
  def update
    @forum = Forum.find(params[:id])

    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to(@forum, :notice => 'Forum was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @forum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.xml
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy

    respond_to do |format|
      format.html { redirect_to(forums_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  # GET /replies
  # GET /replies.xml

before_filter :load_topic
  
  def load_topic
    @topic = Topic.find(params[:topic_id])
  end  

  def index
    @replies = Reply.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @replies }
    end
  end

  # GET /replies/1
  # GET /replies/1.xml
  def show
    @reply = Reply.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reply }
    end
  end

  # GET /replies/new
  # GET /replies/new.xml
  def new
   @reply = @topic.replies.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reply }
    end
  end

  # GET /replies/1/edit
  def edit
    @reply = @topic.replies.find(params[:id])
  end

  # POST /replies
  # POST /replies.xml
  def create
    @reply = @topic.replies.build(params[:reply])

    respond_to do |format|
      if @reply.save
        flash[:notice] = 'Reply was successfully created.'
        format.html { redirect_to([Forum.find(@topic.forum_id), @topic]) }
        format.xml  { render :xml => @reply, :status => :created, :location => @reply }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reply.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /replies/1
  # PUT /replies/1.xml
   def update
    @reply = @topic.replies.find(params[:id])

    respond_to do |format|
      if @reply.update_attributes(params[:reply])
        flash[:notice] = 'Reply was successfully updated.'
        format.html { redirect_to(@topic) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reply.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.xml
  def destroy
    @reply = @topic.replies.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to(@topic) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.xml
 before_filter :load_forum 
def index
    @topics = @forum.topics


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    @topic = @forum.topics.find(params[:id])




    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = @forum.topics.build





    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = @forum.topics.find(params[:id])



  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = @forum.topics.build(params[:topic])

    respond_to do |format|
      if @topic.save
        flash[:notice] = 'Topic was successfully created.'
        format.html { redirect_to(@forum) }
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end




  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = @forum.topics.find(params[:id])



    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to(@forum) }



        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = @forum.topics.find(params[:id])



    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(forum_topics_url(@forum)) }




      format.xml  { head :ok }
    end
  end
end


  
  def load_forum
    @forum = Forum.find(params[:forum_id])
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<h1>Listing forums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @forums.each do |forum| %>
  <tr>
    <td><%= forum.name %></td>
    <td><%= forum.description %></td>
    <td><%= link_to 'Show', forum %></td>
    <td><%= link_to 'Edit', edit_forum_path(forum) %></td>
    <td><%= link_to 'Destroy', forum, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Forum', new_forum_path %>

app/views/forums/new.html.erb
<h1>New forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p>
  <b>Forum:</b>
  <%=h @forum.name %> - <%=h @forum.description %>
</p>

<% unless @forum.topics.empty? %>
  <h2>Topics</h2>
  <% @forum.topics.each do |topic| %>
    <b><%= link_to topic.subject, [@forum, topic] %></b><br />    
  <% end %>
<% end %>

<h2>New Post</h2>
<%= render :partial => @topic = Topic.new, :locals => { :button_name => 'Create' } %>

<%= link_to 'Edit', edit_forum_path(@forum) %> |
<%= link_to 'Back', forums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myforum</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic %><br />
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/_reply.html.erb
<% form_for([@topic, @reply]) do |f| %>
  <p>
    <b>Subject</b><br />
    <%= f.text_field :subject %>
  </p>

  <p>
    <b>Body</b><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit button_name %>
  </p>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= error_messages_for :reply %>

<%= render :partial => @reply, :locals => { :button_name => "Submit" } %>

<%= link_to 'Show', [@topic, @reply] %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <tr>
    <th>Topic</th>
    <th>User</th>
    <th>Subject</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @replies.each do |reply| %>
  <tr>
    <td><%= reply.topic %></td>
    <td><%= reply.user %></td>
    <td><%= reply.subject %></td>
    <td><%= reply.body %></td>
    <td><%= link_to 'Show', reply %></td>
    <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
    <td><%= link_to 'Destroy', reply, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New reply</h1>

<%= error_messages_for :reply %>

<%= render :partial => @reply, :locals => { :button_name => "Reply" } %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Topic:</b>
  <%= @reply.topic %>
</p>

<p>
  <b>User:</b>
  <%= @reply.user %>
</p>

<p>
  <b>Subject:</b>
  <%= @reply.subject %>
</p>

<p>
  <b>Body:</b>
  <%= @reply.body %>
</p>


<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :forum %><br />
    <%= f.text_field :forum %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<% form_for([@forum, @topic]) do |f| %>
  <p>
    <b>Subject</b><br />
    <%= f.text_field :subject %>
  </p>

  <p>
    <b>Body</b><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit button_name %>
  </p>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= error_messages_for :topic %>

<%= render :partial => @topic, :locals => { :button_name => "Submit" } %>

<%= link_to 'Show', [@forum, @topic] %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Forum</th>
    <th>User</th>
    <th>Subject</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.forum %></td>
    <td><%= topic.user %></td>
    <td><%= topic.subject %></td>
    <td><%= topic.body %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= error_messages_for :topic %>

<%= render :partial => @topic, :locals => { :button_name => "Create" } %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p>
  <h3>Forum: - <%=h @forum.name %></h3>
</p>

<p>
  <b><%=h @topic.subject %></b>
</p>

<p>
  <%=h @topic.body %>
</p>

<% unless @topic.replies.empty? %>

  <% @topic.replies.each do |reply| %>
      <p>
        <b><%= reply.subject %></b>    
      </p>
      <p>
        <%=h reply.body %>
      </p>
    
  <% end %>
<% end %>

<h2>Reply</h2>
<%= render :partial => @reply = Reply.new, :locals => { :button_name => 'Reply' } %>

<%= link_to 'Edit', edit_forum_topic_path(@forum, @topic) %> |
<%= link_to 'Back', topics_path %>